/**
 * Optional AI-generated executive summary, appended on top of the deterministic
 * report from generate-report.ts. This step is entirely optional: if
 * AnythingLLM (the user's own instance, over Tailscale) is not reachable,
 * it logs why and exits 0 without touching the report, so the workflow
 * stays fully functional without it. No paid API is used anywhere in this
 * pipeline.
 *
 * The model is instructed, explicitly and repeatedly, to summarize and
 * prioritize only — never to invent a metric, page, or query that isn't
 * already present in the Markdown report it's given. This script does not
 * feed it anything else.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { REPORTS_DIR, isoDate } from './config';
import { generateWithAnythingLLM, getAnythingLLMBaseUrl, isAnythingLLMReachable, AnythingLLMError } from './anythingllm-client';

const SYSTEM_PROMPT = `You are an SEO analyst writing a short executive-summary addendum for a small business owner (Baraka Events, a Lahore, Pakistan event-management company).

You will be given a Markdown SEO report that was generated entirely from real Google Search Console data. Your job is ONLY to summarize and prioritize what is already in that report.

Strict rules:
- Never invent, estimate, or assume any number, page URL, or search query that is not already written in the report you were given.
- Never state a metric more precisely than the report states it.
- If the report shows no notable wins, losses, or issues, say that plainly rather than manufacturing significance.
- Do not recommend specific new content, page changes, or copy — only prioritize which of the report's existing findings deserve attention first, and why.
- Keep it under 200 words, plain prose, no markdown headers (this will be inserted as a section body).`;

async function main() {
  const reportPath = resolve(process.cwd(), REPORTS_DIR, 'latest.md');
  const baseUrl = getAnythingLLMBaseUrl();

  const reachable = await isAnythingLLMReachable();
  if (!reachable) {
    console.log(
      `AnythingLLM is not reachable at ${baseUrl} — skipping the AI summary step. The deterministic report above is unaffected. ` +
        'This is expected unless this job has joined the Tailscale tailnet that can reach it. See SEO_AUTOMATION.md.'
    );
    return;
  }

  if (!existsSync(reportPath)) {
    console.error(`No report found at ${reportPath} — run generate-report.ts first. Skipping AI summary.`);
    return;
  }

  const report = readFileSync(reportPath, 'utf8');
  if (/Search Console (data unavailable|API access is not yet granted)/.test(report)) {
    console.log('Report reflects an auth/permission failure, not real data — skipping AI summary to avoid summarizing an error state.');
    return;
  }

  let summary: string;
  try {
    summary = await generateWithAnythingLLM(report, { system: SYSTEM_PROMPT });
  } catch (err) {
    const message = err instanceof AnythingLLMError ? err.message : err instanceof Error ? err.message : String(err);
    console.error('AI summary request failed — leaving the deterministic report unchanged:', message);
    return;
  }
  if (!summary) {
    console.error('AI summary response contained no text — leaving report unchanged.');
    return;
  }

  const addendum = `\n## AI-assisted executive summary\n\n${summary}\n\n_This section is generated by the site owner's own Qwen3:8b model, running locally via AnythingLLM/Ollama, from the data above, and adds no new facts — see the sections above for every underlying number._\n`;
  const updated = report + addendum;
  writeFileSync(reportPath, updated);
  const datedPath = resolve(process.cwd(), REPORTS_DIR, `report-${isoDate(new Date())}.md`);
  if (existsSync(datedPath)) writeFileSync(datedPath, updated);
  console.log('AI executive summary appended to the report.');
}

main().catch((err) => {
  console.error('Unexpected failure in AI summary step (non-fatal, report already written):', err);
});
