/**
 * Optional AI-generated executive summary, appended on top of the deterministic
 * report from generate-report.ts. This step is entirely optional: if
 * ANTHROPIC_API_KEY is not set, it logs why and exits 0 without touching the
 * report, so the workflow stays fully functional without it.
 *
 * The model is instructed, explicitly and repeatedly, to summarize and
 * prioritize only — never to invent a metric, page, or query that isn't
 * already present in the Markdown report it's given. This script does not
 * feed it anything else.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import Anthropic from '@anthropic-ai/sdk';
import { REPORTS_DIR, isoDate } from './config';

const SYSTEM_PROMPT = `You are an SEO analyst writing a short executive-summary addendum for a small business owner (Baraka Events, a Lahore, Pakistan event-management company).

You will be given a Markdown SEO report that was generated entirely from real Google Search Console data. Your job is ONLY to summarize and prioritize what is already in that report.

Strict rules:
- Never invent, estimate, or assume any number, page URL, or search query that is not already written in the report you were given.
- Never state a metric more precisely than the report states it.
- If the report shows no notable wins, losses, or issues, say that plainly rather than manufacturing significance.
- Do not recommend specific new content, page changes, or copy — only prioritize which of the report's existing findings deserve attention first, and why.
- Keep it under 200 words, plain prose, no markdown headers (this will be inserted as a section body).`;

async function main() {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  const reportPath = resolve(process.cwd(), REPORTS_DIR, 'latest.md');

  if (!apiKey) {
    console.log(
      'ANTHROPIC_API_KEY is not set — skipping the AI summary step. The deterministic report above is unaffected. ' +
        'To enable this step, add an ANTHROPIC_API_KEY repository secret.'
    );
    return;
  }

  if (!existsSync(reportPath)) {
    console.error(`No report found at ${reportPath} — run generate-report.ts first. Skipping AI summary.`);
    return;
  }

  const report = readFileSync(reportPath, 'utf8');
  if (/Search Console (data unavailable|API access is not yet granted)/.test(report)) {
    console.log('Report reflects an auth/permission failure, not real data — skipping AI summary to avoid summarizing an error state.');
    return;
  }

  const client = new Anthropic({ apiKey });

  let summary: string;
  try {
    const response = await client.messages.create({
      model: 'claude-opus-5',
      max_tokens: 1024,
      system: SYSTEM_PROMPT,
      messages: [{ role: 'user', content: report }],
    });
    const textBlock = response.content.find((b): b is Anthropic.TextBlock => b.type === 'text');
    summary = textBlock?.text?.trim() ?? '';
    if (!summary) {
      console.error('AI summary response contained no text — leaving report unchanged.');
      return;
    }
  } catch (err) {
    console.error('AI summary request failed — leaving the deterministic report unchanged:', err instanceof Error ? err.message : err);
    return;
  }

  const addendum = `\n## AI-assisted executive summary\n\n${summary}\n\n_This section is generated by Claude from the data above and adds no new facts — see the sections above for every underlying number._\n`;
  const updated = report + addendum;
  writeFileSync(reportPath, updated);
  const datedPath = resolve(process.cwd(), REPORTS_DIR, `report-${isoDate(new Date())}.md`);
  if (existsSync(datedPath)) writeFileSync(datedPath, updated);
  console.log('AI executive summary appended to the report.');
}

main().catch((err) => {
  console.error('Unexpected failure in AI summary step (non-fatal, report already written):', err);
});
